// var Messages = function(input) {
//     //we think this is the Model

//     // store the data that we get from the server
//       // then do something with it 

//     //input string
//     //should have prop 
//         //username:
//         // App.username is inherited from contructor
//             // was generated by a method that grabs the user input
//     //we will pass the msg along with the onclick function, when invoked
//         //submit(this.msg)
  
//         // to get text (or new messages) 
//             // might need to use Parse.readAll() to get the message 
//                // need to access the text part of the message

//                $message: $('message'),
//                //referenced in messagesview 
//                //chat is one message 
//                //we think this is the view - create NODE here -
//                //associated w/ 0 or 1 model objects
//                //inheirent from messages.js
             
//             //    currentUser: '',
//             //    currentText: '',
               
//                // initialize: function() {
//                //   // MessageView.$message.on('submit', MessageView.render);
             
//                //   // what is the initialize function supposed to do?
//                //     // we need to invoke the below template
//                // },
//             //    arrayStorage: Parse.readAll(),
               
//             //    initialize: function() {
//             //      for (var i = 0; i < MessageView.arrayStorage.results.length; i++) {
//             //        var newArr = MessageView.arrayStorage.results;
//             //        MessageView.currentUser = newArr[i].username;
//             //        MessageView.currentText = newArr[i].text;
//             //        MessageView.render();
//             //      }
//             //    },

// };

