var Messages = function(input) {
    //input string
    //should have prop 
        //username:
        // App.username is inherited from contructor
            // was generated by a method that grabs the user input
        this.username = App.username;
        //text:
          // message that is typed into textbox (next to submit)
        this.text;
        //roomname:
        this.roomname;
        this.msg = input;//users input msg - not sure yet
    //we will pass the msg along with the onclick function, when invoked
        //submit(this.msg)

};

